import type {Metadata} from "next";
import "./globals.css";
import NavBar from "../components/navBar";


export const metadata: Metadata = {
    title: "Next Js Challenge",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={"bg-white"} >
                <NavBar/>
                {children}
            </body>
        </html>
    );
}
