import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import NavBar from "../components/nav-bar";


export const metadata: Metadata = {
    title: "Next Js Challenge",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={'bg-white'} >
        <NavBar/>
        {children}
        </body>
        </html>
    );
}
